# Generated by Django 5.0.7 on 2025-05-26 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSelectionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category_name_eng', models.CharField(default='', max_length=80)),
                ('main_category_name_arb', models.CharField(default='', max_length=80)),
                ('duration_delivery_period', models.CharField(default='', max_length=80)),
                ('initial_price', models.DecimalField(decimal_places=3, max_digits=9)),
                ('cover', models.DecimalField(decimal_places=3, max_digits=9)),
                ('review_rate', models.IntegerField(default=0)),
                ('isHidden', models.BooleanField(default=False)),
                ('is_comming_soon', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name_eng', models.CharField(default='', max_length=80)),
                ('category_name_arb', models.CharField(default='', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name_eng', models.CharField(max_length=300)),
                ('product_name_arb', models.CharField(max_length=300)),
                ('initial_price', models.DecimalField(decimal_places=3, max_digits=9)),
                ('quantity', models.IntegerField(default=0)),
                ('inStock', models.BooleanField(default=True)),
                ('isHidden', models.BooleanField(default=False)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='media/Products/')),
                ('color', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(blank=True, related_name='product_category', to='Design.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='GholaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ghola_type_name_eng', models.CharField(max_length=300)),
                ('ghola_type_name_arb', models.CharField(max_length=300)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('inStock', models.BooleanField(default=True)),
                ('initial_price', models.DecimalField(decimal_places=3, max_digits=9)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='media/GholaType/')),
                ('fabric_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Design.product')),
                ('category', models.ManyToManyField(blank=True, related_name='ghola_product_category', to='Design.productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='SleevesType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sleeves_type_name_eng', models.CharField(max_length=300)),
                ('sleeves_type_name_arb', models.CharField(max_length=300)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('inStock', models.BooleanField(default=True)),
                ('initial_price', models.DecimalField(decimal_places=3, max_digits=9)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='media/SleevesType/')),
                ('category', models.ManyToManyField(blank=True, related_name='sleeve_product_category', to='Design.productcategory')),
                ('fabric_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Design.product')),
            ],
        ),
    ]
