# Generated by Django 5.0.7 on 2025-05-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Design', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepageselectioncategory',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='media/MainCat/'),
        ),
    ]
