# Generated by Django 5.0.7 on 2025-05-27 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Design', '0002_alter_homepageselectioncategory_cover'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_Total', models.DecimalField(decimal_places=3, default=0.0, max_digits=9)),
                ('initial_size_selected', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Design.homepageselectioncategory')),
                ('main_body_fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Design.product')),
                ('selected_coller_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Design.gholatype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
