# Generated by Django 5.0.7 on 2025-06-04 15:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Design', '0003_userdesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdesign',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
