# Generated by Django 5.0.7 on 2025-06-04 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Design', '0004_userdesign_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleevestype',
            name='is_right_side',
            field=models.BooleanField(default=False),
        ),
    ]
