# Generated by Django 5.0.7 on 2025-06-09 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Design', '0005_sleevestype_is_right_side'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdesign',
            name='selected_sleeve_left_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_sleeve_left_type', to='Design.sleevestype'),
        ),
        migrations.AddField(
            model_name='userdesign',
            name='selected_sleeve_right_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Design.sleevestype'),
        ),
    ]
