# Generated by Django 5.0.7 on 2025-10-30 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Design', '0006_userdesign_selected_sleeve_left_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonStripType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_strip_type_name_eng', models.CharField(max_length=300)),
                ('button_strip_type_name_arb', models.CharField(max_length=300)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('inStock', models.BooleanField(default=True)),
                ('initial_price', models.DecimalField(decimal_places=3, max_digits=9)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='media/ButtonStripType/')),
                ('category', models.ManyToManyField(blank=True, related_name='button_strip_product_category', to='Design.productcategory')),
                ('fabric_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Design.product')),
            ],
        ),
        migrations.CreateModel(
            name='ButtonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_type_name_eng', models.CharField(max_length=300)),
                ('button_type_name_arb', models.CharField(max_length=300)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('inStock', models.BooleanField(default=True)),
                ('initial_price', models.DecimalField(decimal_places=3, max_digits=9)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='media/ButtonType/')),
                ('category', models.ManyToManyField(blank=True, related_name='button_product_category', to='Design.productcategory')),
                ('fabric_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Design.product')),
            ],
        ),
        migrations.CreateModel(
            name='PocketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pocket_type_name_eng', models.CharField(max_length=300)),
                ('pocket_type_name_arb', models.CharField(max_length=300)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('color', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('inStock', models.BooleanField(default=True)),
                ('initial_price', models.DecimalField(decimal_places=3, max_digits=9)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='media/PocketType/')),
                ('category', models.ManyToManyField(blank=True, related_name='pocket_product_category', to='Design.productcategory')),
                ('fabric_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Design.product')),
            ],
        ),
    ]
