# Generated by Django 5.0.7 on 2025-11-01 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Design', '0008_alter_buttonstriptype_cover_alter_buttontype_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdesign',
            name='selected_button_strip_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_button_strip_designs', to='Design.buttonstriptype'),
        ),
        migrations.AddField(
            model_name='userdesign',
            name='selected_button_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_button_designs', to='Design.buttontype'),
        ),
        migrations.AddField(
            model_name='userdesign',
            name='selected_pocket_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_pocket_designs', to='Design.pockettype'),
        ),
    ]
