# Generated by Django 5.0.7 on 2025-11-01 07:32

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Design', '0009_userdesign_selected_button_strip_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FabricColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name_eng', models.CharField(max_length=100)),
                ('color_name_arb', models.CharField(max_length=100)),
                ('cover', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('quantity', models.IntegerField(default=0)),
                ('inStock', models.BooleanField(default=True)),
                ('price_adjustment', models.DecimalField(decimal_places=3, default=0.0, help_text='Additional price for this color (can be positive or negative)', max_digits=9)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fabric Color',
                'verbose_name_plural': 'Fabric Colors',
            },
        ),
        migrations.AlterModelOptions(
            name='buttonstriptype',
            options={'verbose_name': 'Button Strip Type', 'verbose_name_plural': 'Button Strip Types'},
        ),
        migrations.AlterModelOptions(
            name='buttontype',
            options={'verbose_name': 'Button Type', 'verbose_name_plural': 'Button Types'},
        ),
        migrations.AlterModelOptions(
            name='gholatype',
            options={'verbose_name': 'Collar Type (Ghola)', 'verbose_name_plural': 'Collar Types (Ghola)'},
        ),
        migrations.AlterModelOptions(
            name='pockettype',
            options={'verbose_name': 'Pocket Type', 'verbose_name_plural': 'Pocket Types'},
        ),
        migrations.AlterModelOptions(
            name='sleevestype',
            options={'verbose_name': 'Sleeve Type', 'verbose_name_plural': 'Sleeve Types'},
        ),
        migrations.AlterModelOptions(
            name='userdesign',
            options={'verbose_name': 'User Design', 'verbose_name_plural': 'User Designs'},
        ),
        migrations.RemoveField(
            model_name='buttonstriptype',
            name='color',
        ),
        migrations.RemoveField(
            model_name='buttontype',
            name='color',
        ),
        migrations.RemoveField(
            model_name='gholatype',
            name='color',
        ),
        migrations.RemoveField(
            model_name='pockettype',
            name='color',
        ),
        migrations.RemoveField(
            model_name='sleevestype',
            name='color',
        ),
        migrations.AlterField(
            model_name='buttonstriptype',
            name='fabric_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Design.product'),
        ),
        migrations.AlterField(
            model_name='buttontype',
            name='fabric_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Design.product'),
        ),
        migrations.AlterField(
            model_name='gholatype',
            name='fabric_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Design.product'),
        ),
        migrations.AlterField(
            model_name='pockettype',
            name='fabric_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Design.product'),
        ),
        migrations.AlterField(
            model_name='sleevestype',
            name='fabric_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Design.product'),
        ),
        migrations.AlterField(
            model_name='userdesign',
            name='main_body_fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Design.product'),
        ),
        migrations.AddField(
            model_name='buttonstriptype',
            name='fabric_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='button_strip_types', to='Design.fabriccolor'),
        ),
        migrations.AddField(
            model_name='buttontype',
            name='fabric_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='button_types', to='Design.fabriccolor'),
        ),
        migrations.AddField(
            model_name='gholatype',
            name='fabric_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ghola_types', to='Design.fabriccolor'),
        ),
        migrations.AddField(
            model_name='pockettype',
            name='fabric_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pocket_types', to='Design.fabriccolor'),
        ),
        migrations.AddField(
            model_name='sleevestype',
            name='fabric_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sleeve_types', to='Design.fabriccolor'),
        ),
        migrations.AddField(
            model_name='userdesign',
            name='main_body_fabric_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_designs', to='Design.fabriccolor'),
        ),
        migrations.CreateModel(
            name='FabricType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_name_eng', models.CharField(max_length=300)),
                ('fabric_name_arb', models.CharField(max_length=300)),
                ('base_price', models.DecimalField(decimal_places=3, max_digits=9)),
                ('cover', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('isHidden', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(blank=True, related_name='fabric_type_category', to='Design.productcategory')),
            ],
            options={
                'verbose_name': 'Fabric Type',
                'verbose_name_plural': 'Fabric Types',
            },
        ),
        migrations.AddField(
            model_name='fabriccolor',
            name='fabric_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='Design.fabrictype'),
        ),
        migrations.AlterUniqueTogether(
            name='fabriccolor',
            unique_together={('fabric_type', 'color_name_eng')},
        ),
    ]
