# Generated by Django 5.0.7 on 2025-11-21 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Design', '0011_inventorytransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabrictype',
            name='category_type',
            field=models.CharField(choices=[('premium', 'Premium'), ('standard', 'Standard'), ('economy', 'Economy'), ('luxury', 'Luxury')], default='standard', help_text='Fabric category: Premium, Standard, etc.', max_length=20),
        ),
        migrations.AddField(
            model_name='fabrictype',
            name='composition',
            field=models.CharField(blank=True, help_text="Fabric composition e.g., '100% Polyester'", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fabrictype',
            name='composition_arb',
            field=models.CharField(blank=True, help_text='Fabric composition in Arabic', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fabrictype',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text="List of features e.g., ['Anti-Static', 'Anti-Breakable', 'Easy Iron']"),
        ),
        migrations.AddField(
            model_name='fabrictype',
            name='features_arb',
            field=models.JSONField(blank=True, default=list, help_text='List of features in Arabic'),
        ),
        migrations.AddField(
            model_name='fabrictype',
            name='originality',
            field=models.CharField(blank=True, help_text='Origin country e.g., Kuwait, Italy', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fabrictype',
            name='originality_arb',
            field=models.CharField(blank=True, help_text='Origin country in Arabic', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fabrictype',
            name='season',
            field=models.CharField(choices=[('summer', 'Summer'), ('winter', 'Winter'), ('all_season', 'All Season'), ('spring', 'Spring'), ('autumn', 'Autumn')], default='all_season', max_length=20),
        ),
        migrations.AddField(
            model_name='fabrictype',
            name='softness_grade',
            field=models.IntegerField(default=3, help_text='Softness to Solidness grade from 1 (Soft) to 5 (Solid)'),
        ),
        migrations.AddField(
            model_name='fabrictype',
            name='weight',
            field=models.CharField(blank=True, help_text="Weight description e.g., 'per sq / m'", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fabrictype',
            name='weight_arb',
            field=models.CharField(blank=True, help_text='Weight description in Arabic', max_length=50, null=True),
        ),
    ]
