# Generated by Django 5.0.7 on 2025-11-21 11:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Design', '0012_fabrictype_category_type_fabrictype_composition_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userdesign',
            name='design_name',
            field=models.CharField(blank=True, help_text='Custom name for this design', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userdesign',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to=settings.AUTH_USER_MODEL),
        ),
    ]
