# Generated by Django 5.0.7 on 2025-11-25 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Design', '0013_userdesign_design_name_alter_userdesign_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buttonstriptype',
            name='fabric_type',
        ),
        migrations.RemoveField(
            model_name='buttontype',
            name='fabric_type',
        ),
        migrations.RemoveField(
            model_name='pockettype',
            name='fabric_type',
        ),
        migrations.RemoveField(
            model_name='gholatype',
            name='fabric_type',
        ),
        migrations.RemoveField(
            model_name='sleevestype',
            name='fabric_type',
        ),
        migrations.RemoveField(
            model_name='userdesign',
            name='main_body_fabric',
        ),
        migrations.RemoveField(
            model_name='pockettype',
            name='category',
        ),
        migrations.RemoveField(
            model_name='gholatype',
            name='category',
        ),
        migrations.RemoveField(
            model_name='fabrictype',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sleevestype',
            name='category',
        ),
        migrations.RemoveField(
            model_name='buttonstriptype',
            name='category',
        ),
        migrations.RemoveField(
            model_name='buttontype',
            name='category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
