# Generated by Django 5.0.7 on 2025-11-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Design', '0014_remove_buttonstriptype_fabric_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabriccolor',
            name='hex_color',
            field=models.CharField(default='#FFFFFF', help_text='Hex color code (e.g., #FFFFFF)', max_length=7),
        ),
    ]
