# Generated by Django 5.0.7 on 2025-11-25 15:45

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Design', '0015_fabriccolor_hex_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_type_name_eng', models.CharField(max_length=300)),
                ('body_type_name_arb', models.CharField(max_length=300)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('inStock', models.BooleanField(default=True)),
                ('initial_price', models.DecimalField(decimal_places=3, max_digits=9)),
                ('cover', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('fabric_color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='body_types', to='Design.fabriccolor')),
            ],
            options={
                'verbose_name': 'Body Type',
                'verbose_name_plural': 'Body Types',
            },
        ),
        migrations.AddField(
            model_name='userdesign',
            name='selected_body_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_body_designs', to='Design.bodytype'),
        ),
    ]
