# Generated by Django 5.0.7 on 2025-11-26 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Design', '0016_bodytype_userdesign_selected_body_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodytype',
            name='fabric_color',
        ),
        migrations.RemoveField(
            model_name='buttonstriptype',
            name='fabric_color',
        ),
        migrations.RemoveField(
            model_name='buttontype',
            name='fabric_color',
        ),
        migrations.RemoveField(
            model_name='gholatype',
            name='fabric_color',
        ),
        migrations.RemoveField(
            model_name='pockettype',
            name='fabric_color',
        ),
        migrations.RemoveField(
            model_name='sleevestype',
            name='fabric_color',
        ),
        migrations.AddField(
            model_name='bodytype',
            name='color',
            field=models.CharField(default='White', help_text='Color name (e.g., White, Black, Navy)', max_length=100),
        ),
        migrations.AddField(
            model_name='bodytype',
            name='fabric_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='body_types', to='Design.fabrictype'),
        ),
        migrations.AddField(
            model_name='buttonstriptype',
            name='color',
            field=models.CharField(default='White', help_text='Color name (e.g., White, Black, Navy)', max_length=100),
        ),
        migrations.AddField(
            model_name='buttonstriptype',
            name='fabric_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='button_strip_types', to='Design.fabrictype'),
        ),
        migrations.AddField(
            model_name='buttontype',
            name='color',
            field=models.CharField(default='White', help_text='Color name (e.g., White, Black, Navy)', max_length=100),
        ),
        migrations.AddField(
            model_name='buttontype',
            name='fabric_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='button_types', to='Design.fabrictype'),
        ),
        migrations.AddField(
            model_name='gholatype',
            name='color',
            field=models.CharField(default='White', help_text='Color name (e.g., White, Black, Navy)', max_length=100),
        ),
        migrations.AddField(
            model_name='gholatype',
            name='fabric_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ghola_types', to='Design.fabrictype'),
        ),
        migrations.AddField(
            model_name='pockettype',
            name='color',
            field=models.CharField(default='White', help_text='Color name (e.g., White, Black, Navy)', max_length=100),
        ),
        migrations.AddField(
            model_name='pockettype',
            name='fabric_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pocket_types', to='Design.fabrictype'),
        ),
        migrations.AddField(
            model_name='sleevestype',
            name='color',
            field=models.CharField(default='White', help_text='Color name (e.g., White, Black, Navy)', max_length=100),
        ),
        migrations.AddField(
            model_name='sleevestype',
            name='fabric_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sleeve_types', to='Design.fabrictype'),
        ),
    ]
