# Generated by Django 5.0.7 on 2025-11-26 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Design', '0017_remove_bodytype_fabric_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodytype',
            name='color',
        ),
        migrations.RemoveField(
            model_name='buttonstriptype',
            name='color',
        ),
        migrations.RemoveField(
            model_name='buttontype',
            name='color',
        ),
        migrations.RemoveField(
            model_name='gholatype',
            name='color',
        ),
        migrations.RemoveField(
            model_name='pockettype',
            name='color',
        ),
        migrations.RemoveField(
            model_name='sleevestype',
            name='color',
        ),
        migrations.AddField(
            model_name='bodytype',
            name='fabric_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='body_types', to='Design.fabriccolor'),
        ),
        migrations.AddField(
            model_name='buttonstriptype',
            name='fabric_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='button_strip_types', to='Design.fabriccolor'),
        ),
        migrations.AddField(
            model_name='buttontype',
            name='fabric_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='button_types', to='Design.fabriccolor'),
        ),
        migrations.AddField(
            model_name='gholatype',
            name='fabric_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ghola_types', to='Design.fabriccolor'),
        ),
        migrations.AddField(
            model_name='pockettype',
            name='fabric_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pocket_types', to='Design.fabriccolor'),
        ),
        migrations.AddField(
            model_name='sleevestype',
            name='fabric_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sleeve_types', to='Design.fabriccolor'),
        ),
    ]
