# Generated by Django 5.0.7 on 2025-12-03 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Design', '0018_remove_bodytype_color_remove_buttonstriptype_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodytype',
            name='inStock',
        ),
        migrations.RemoveField(
            model_name='buttonstriptype',
            name='inStock',
        ),
        migrations.RemoveField(
            model_name='gholatype',
            name='inStock',
        ),
        migrations.RemoveField(
            model_name='pockettype',
            name='inStock',
        ),
        migrations.RemoveField(
            model_name='sleevestype',
            name='inStock',
        ),
    ]
