# Generated by Django 5.0.7 on 2025-12-18 10:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Design', '0019_remove_bodytype_instock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodytype',
            name='cover_option',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Image shown in selection cards/options', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='buttonstriptype',
            name='cover_option',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Image shown in selection cards/options', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='buttontype',
            name='cover_option',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Image shown in selection cards/options', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='gholatype',
            name='cover_option',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Image shown in selection cards/options', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='pockettype',
            name='cover_option',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Image shown in selection cards/options', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='sleevestype',
            name='cover_option',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Image shown in selection cards/options', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='bodytype',
            name='cover',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Image shown on dishdasha preview', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='buttonstriptype',
            name='cover',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Image shown on dishdasha preview', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='buttontype',
            name='cover',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Image shown on dishdasha preview', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='gholatype',
            name='cover',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Image shown on dishdasha preview', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='pockettype',
            name='cover',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Image shown on dishdasha preview', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='sleevestype',
            name='cover',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Image shown on dishdasha preview', max_length=255, null=True, verbose_name='image'),
        ),
    ]
