# Generated by Django 5.1.4 on 2025-12-20 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Design', '0020_bodytype_cover_option_buttonstriptype_cover_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdesign',
            name='initial_size_selected',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_designs_category', to='Design.homepageselectioncategory'),
        ),
        migrations.AlterField(
            model_name='userdesign',
            name='selected_coller_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_collar_designs', to='Design.gholatype'),
        ),
    ]
