# Generated by Django 5.1.4 on 2025-12-26 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Design', '0022_gholatype_is_button_hidden'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_hash', models.CharField(db_index=True, help_text='MD5 hash of all component IDs to uniquely identify design configuration', max_length=64, unique=True)),
                ('screenshot_url', models.URLField(help_text='Cloudinary URL of the design screenshot', max_length=500)),
                ('cloudinary_public_id', models.CharField(blank=True, help_text='Cloudinary public ID for managing the image', max_length=255, null=True)),
                ('fabric_color_id', models.IntegerField(blank=True, null=True)),
                ('collar_id', models.IntegerField(blank=True, null=True)),
                ('sleeve_left_id', models.IntegerField(blank=True, null=True)),
                ('sleeve_right_id', models.IntegerField(blank=True, null=True)),
                ('pocket_id', models.IntegerField(blank=True, null=True)),
                ('button_id', models.IntegerField(blank=True, null=True)),
                ('button_strip_id', models.IntegerField(blank=True, null=True)),
                ('body_id', models.IntegerField(blank=True, null=True)),
                ('times_reused', models.IntegerField(default=0, help_text='Number of times this screenshot was reused instead of regenerating')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Design Screenshot',
                'verbose_name_plural': 'Design Screenshots',
                'ordering': ['-created_at'],
            },
        ),
    ]
