# Generated by Django 5.1.4 on 2026-01-11 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Design', '0023_designscreenshot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodytype',
            options={'ordering': ['-priority', '-timestamp'], 'verbose_name': 'Body Type', 'verbose_name_plural': 'Body Types'},
        ),
        migrations.AlterModelOptions(
            name='buttonstriptype',
            options={'ordering': ['-priority', '-timestamp'], 'verbose_name': 'Button Strip Type', 'verbose_name_plural': 'Button Strip Types'},
        ),
        migrations.AlterModelOptions(
            name='buttontype',
            options={'ordering': ['-priority', '-timestamp'], 'verbose_name': 'Button Type', 'verbose_name_plural': 'Button Types'},
        ),
        migrations.AlterModelOptions(
            name='fabriccolor',
            options={'ordering': ['-priority', '-timestamp'], 'verbose_name': 'Fabric Color', 'verbose_name_plural': 'Fabric Colors'},
        ),
        migrations.AlterModelOptions(
            name='fabrictype',
            options={'ordering': ['-priority', '-timestamp'], 'verbose_name': 'Fabric Type', 'verbose_name_plural': 'Fabric Types'},
        ),
        migrations.AlterModelOptions(
            name='gholatype',
            options={'ordering': ['-priority', '-timestamp'], 'verbose_name': 'Collar Type (Ghola)', 'verbose_name_plural': 'Collar Types (Ghola)'},
        ),
        migrations.AlterModelOptions(
            name='pockettype',
            options={'ordering': ['-priority', '-timestamp'], 'verbose_name': 'Pocket Type', 'verbose_name_plural': 'Pocket Types'},
        ),
        migrations.AlterModelOptions(
            name='sleevestype',
            options={'ordering': ['-priority', '-timestamp'], 'verbose_name': 'Sleeve Type', 'verbose_name_plural': 'Sleeve Types'},
        ),
        migrations.AddField(
            model_name='bodytype',
            name='priority',
            field=models.IntegerField(default=0, help_text='Higher value = higher priority in display'),
        ),
        migrations.AddField(
            model_name='buttonstriptype',
            name='priority',
            field=models.IntegerField(default=0, help_text='Higher value = higher priority in display'),
        ),
        migrations.AddField(
            model_name='buttontype',
            name='priority',
            field=models.IntegerField(default=0, help_text='Higher value = higher priority in display'),
        ),
        migrations.AddField(
            model_name='fabriccolor',
            name='priority',
            field=models.IntegerField(default=0, help_text='Higher value = higher priority in display'),
        ),
        migrations.AddField(
            model_name='fabrictype',
            name='priority',
            field=models.IntegerField(default=0, help_text='Higher value = higher priority in display'),
        ),
        migrations.AddField(
            model_name='gholatype',
            name='priority',
            field=models.IntegerField(default=0, help_text='Higher value = higher priority in display'),
        ),
        migrations.AddField(
            model_name='homepageselectioncategory',
            name='priority',
            field=models.IntegerField(default=0, help_text='Higher value = higher priority in display'),
        ),
        migrations.AddField(
            model_name='pockettype',
            name='priority',
            field=models.IntegerField(default=0, help_text='Higher value = higher priority in display'),
        ),
        migrations.AddField(
            model_name='sleevestype',
            name='priority',
            field=models.IntegerField(default=0, help_text='Higher value = higher priority in display'),
        ),
    ]
