# Generated by Django 5.1.4 on 2026-01-11 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Design', '0024_alter_bodytype_options_alter_buttonstriptype_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdesign',
            name='selected_button_strip_type',
        ),
        migrations.AlterModelOptions(
            name='bodytype',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Body Type', 'verbose_name_plural': 'Body Types'},
        ),
        migrations.RemoveField(
            model_name='bodytype',
            name='priority',
        ),
        migrations.DeleteModel(
            name='ButtonStripType',
        ),
    ]
