# Generated by Django 5.1.4 on 2026-01-11 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Design', '0025_remove_userdesign_selected_button_strip_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designscreenshot',
            name='button_strip_id',
        ),
    ]
