# Generated by Django 5.1.4 on 2026-01-11 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Design', '0026_remove_designscreenshot_button_strip_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buttontype',
            options={'ordering': ['priority', '-timestamp'], 'verbose_name': 'Button Type', 'verbose_name_plural': 'Button Types'},
        ),
        migrations.AlterModelOptions(
            name='fabriccolor',
            options={'ordering': ['priority', '-timestamp'], 'verbose_name': 'Fabric Color', 'verbose_name_plural': 'Fabric Colors'},
        ),
        migrations.AlterModelOptions(
            name='fabrictype',
            options={'ordering': ['priority', '-timestamp'], 'verbose_name': 'Fabric Type', 'verbose_name_plural': 'Fabric Types'},
        ),
        migrations.AlterModelOptions(
            name='gholatype',
            options={'ordering': ['priority', '-timestamp'], 'verbose_name': 'Collar Type (Ghola)', 'verbose_name_plural': 'Collar Types (Ghola)'},
        ),
        migrations.AlterModelOptions(
            name='homepageselectioncategory',
            options={'ordering': ['priority', '-timestamp'], 'verbose_name': 'Home Page Selection Category', 'verbose_name_plural': 'Home Page Selection Categories'},
        ),
        migrations.AlterModelOptions(
            name='pockettype',
            options={'ordering': ['priority', '-timestamp'], 'verbose_name': 'Pocket Type', 'verbose_name_plural': 'Pocket Types'},
        ),
        migrations.AlterModelOptions(
            name='sleevestype',
            options={'ordering': ['priority', '-timestamp'], 'verbose_name': 'Sleeve Type', 'verbose_name_plural': 'Sleeve Types'},
        ),
        migrations.AddField(
            model_name='homepageselectioncategory',
            name='review_count',
            field=models.IntegerField(default=0, help_text='Total number of reviews'),
        ),
        migrations.AlterField(
            model_name='buttontype',
            name='priority',
            field=models.IntegerField(default=0, help_text='Lower value = higher priority (appears first)'),
        ),
        migrations.AlterField(
            model_name='fabriccolor',
            name='priority',
            field=models.IntegerField(default=0, help_text='Lower value = higher priority (appears first)'),
        ),
        migrations.AlterField(
            model_name='fabrictype',
            name='priority',
            field=models.IntegerField(default=0, help_text='Lower value = higher priority (appears first)'),
        ),
        migrations.AlterField(
            model_name='gholatype',
            name='priority',
            field=models.IntegerField(default=0, help_text='Lower value = higher priority (appears first)'),
        ),
        migrations.AlterField(
            model_name='homepageselectioncategory',
            name='priority',
            field=models.IntegerField(default=0, help_text='Lower value = higher priority (appears first)'),
        ),
        migrations.AlterField(
            model_name='homepageselectioncategory',
            name='review_rate',
            field=models.IntegerField(default=5, help_text='Rating from 1 to 5'),
        ),
        migrations.AlterField(
            model_name='pockettype',
            name='priority',
            field=models.IntegerField(default=0, help_text='Lower value = higher priority (appears first)'),
        ),
        migrations.AlterField(
            model_name='sleevestype',
            name='priority',
            field=models.IntegerField(default=0, help_text='Lower value = higher priority (appears first)'),
        ),
    ]
