# Generated by Django 5.1.4 on 2026-01-11 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Design', '0027_alter_buttontype_options_alter_fabriccolor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodytype',
            name='fabric_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='body_types', to='Design.fabriccolor'),
        ),
        migrations.AlterField(
            model_name='bodytype',
            name='fabric_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='body_types', to='Design.fabrictype'),
        ),
        migrations.AlterField(
            model_name='buttontype',
            name='fabric_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='button_types', to='Design.fabriccolor'),
        ),
        migrations.AlterField(
            model_name='buttontype',
            name='fabric_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='button_types', to='Design.fabrictype'),
        ),
        migrations.AlterField(
            model_name='fabriccolor',
            name='fabric_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='colors', to='Design.fabrictype'),
        ),
        migrations.AlterField(
            model_name='gholatype',
            name='fabric_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ghola_types', to='Design.fabriccolor'),
        ),
        migrations.AlterField(
            model_name='gholatype',
            name='fabric_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ghola_types', to='Design.fabrictype'),
        ),
        migrations.AlterField(
            model_name='pockettype',
            name='fabric_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pocket_types', to='Design.fabriccolor'),
        ),
        migrations.AlterField(
            model_name='pockettype',
            name='fabric_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pocket_types', to='Design.fabrictype'),
        ),
        migrations.AlterField(
            model_name='sleevestype',
            name='fabric_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sleeve_types', to='Design.fabriccolor'),
        ),
        migrations.AlterField(
            model_name='sleevestype',
            name='fabric_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sleeve_types', to='Design.fabrictype'),
        ),
        migrations.AlterField(
            model_name='userdesign',
            name='main_body_fabric_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_designs', to='Design.fabriccolor'),
        ),
        migrations.AlterField(
            model_name='userdesign',
            name='selected_body_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_body_designs', to='Design.bodytype'),
        ),
        migrations.AlterField(
            model_name='userdesign',
            name='selected_button_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_button_designs', to='Design.buttontype'),
        ),
        migrations.AlterField(
            model_name='userdesign',
            name='selected_coller_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_collar_designs', to='Design.gholatype'),
        ),
        migrations.AlterField(
            model_name='userdesign',
            name='selected_pocket_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_pocket_designs', to='Design.pockettype'),
        ),
        migrations.AlterField(
            model_name='userdesign',
            name='selected_sleeve_left_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_sleeve_left_type', to='Design.sleevestype'),
        ),
        migrations.AlterField(
            model_name='userdesign',
            name='selected_sleeve_right_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Design.sleevestype'),
        ),
    ]
