# Generated by Django 5.1.4 on 2026-01-11 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Design', '0028_alter_bodytype_fabric_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabriccolor',
            name='fabric_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='Design.fabrictype'),
        ),
    ]
