# Generated by Django 6.0.3 on 2026-03-06 05:46

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Design", "0029_alter_fabriccolor_fabric_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="bodytype",
            name="glb_model",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="3D GLB model file for Unity rendering",
                max_length=255,
                null=True,
                verbose_name="raw",
            ),
        ),
        migrations.AddField(
            model_name="buttontype",
            name="glb_model",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="3D GLB model file for Unity rendering",
                max_length=255,
                null=True,
                verbose_name="raw",
            ),
        ),
        migrations.AddField(
            model_name="fabriccolor",
            name="metallic",
            field=models.FloatField(
                default=0.0,
                help_text="Metallic value for 3D rendering (0=matte, 1=fully metallic)",
            ),
        ),
        migrations.AddField(
            model_name="fabriccolor",
            name="smoothness",
            field=models.FloatField(
                default=0.5,
                help_text="Smoothness value for 3D rendering (0=rough, 1=smooth)",
            ),
        ),
        migrations.AddField(
            model_name="fabriccolor",
            name="texture_image",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="Seamless tileable texture image for 3D rendering (512x512 or 1024x1024)",
                max_length=255,
                null=True,
                verbose_name="image",
            ),
        ),
        migrations.AddField(
            model_name="gholatype",
            name="glb_model",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="3D GLB model file for Unity rendering",
                max_length=255,
                null=True,
                verbose_name="raw",
            ),
        ),
        migrations.AddField(
            model_name="pockettype",
            name="glb_model",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="3D GLB model file for Unity rendering",
                max_length=255,
                null=True,
                verbose_name="raw",
            ),
        ),
        migrations.AddField(
            model_name="sleevestype",
            name="glb_model",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                help_text="3D GLB model file for Unity rendering",
                max_length=255,
                null=True,
                verbose_name="raw",
            ),
        ),
    ]
