# Generated by Django 5.1.4 on 2026-03-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Design', '0029_alter_fabriccolor_fabric_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodytype',
            name='anchor_point',
            field=models.CharField(blank=True, help_text='Anchor point string/coordinates', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bodytype',
            name='glb_model',
            field=models.URLField(blank=True, help_text='Cloudinary URL of the .glb file', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='bodytype',
            name='glb_name',
            field=models.CharField(blank=True, help_text='Custom name for the .glb file', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='buttontype',
            name='anchor_point',
            field=models.CharField(blank=True, help_text='Anchor point string/coordinates', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='buttontype',
            name='glb_model',
            field=models.URLField(blank=True, help_text='Cloudinary URL of the .glb file', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='buttontype',
            name='glb_name',
            field=models.CharField(blank=True, help_text='Custom name for the .glb file', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gholatype',
            name='anchor_point',
            field=models.CharField(blank=True, help_text='Anchor point string/coordinates', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gholatype',
            name='glb_model',
            field=models.URLField(blank=True, help_text='Cloudinary URL of the .glb file', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='gholatype',
            name='glb_name',
            field=models.CharField(blank=True, help_text='Custom name for the .glb file', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pockettype',
            name='anchor_point',
            field=models.CharField(blank=True, help_text='Anchor point string/coordinates', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pockettype',
            name='glb_model',
            field=models.URLField(blank=True, help_text='Cloudinary URL of the .glb file', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pockettype',
            name='glb_name',
            field=models.CharField(blank=True, help_text='Custom name for the .glb file', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sleevestype',
            name='anchor_point',
            field=models.CharField(blank=True, help_text='Anchor point string/coordinates', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sleevestype',
            name='glb_model',
            field=models.URLField(blank=True, help_text='Cloudinary URL of the .glb file', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sleevestype',
            name='glb_name',
            field=models.CharField(blank=True, help_text='Custom name for the .glb file', max_length=200, null=True),
        ),
    ]
