# Generated by Django 5.1.4 on 2026-03-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Design', '0030_bodytype_anchor_point_bodytype_glb_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabrictype',
            name='texture_file',
            field=models.URLField(blank=True, help_text='Cloudinary URL of the texture image file', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='fabrictype',
            name='texture_name',
            field=models.CharField(blank=True, help_text='Custom name for the texture file', max_length=200, null=True),
        ),
    ]
