# Generated by Django 5.0.7 on 2025-12-08 16:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Coupon code (e.g., BETA50, WELCOME10)', max_length=50, unique=True)),
                ('name_en', models.CharField(help_text='Coupon name in English', max_length=100)),
                ('name_ar', models.CharField(help_text='Coupon name in Arabic', max_length=100)),
                ('description_en', models.TextField(blank=True, help_text='Coupon description in English', null=True)),
                ('description_ar', models.TextField(blank=True, help_text='Coupon description in Arabic', null=True)),
                ('coupon_type', models.CharField(choices=[('beta', 'Beta Code'), ('card', 'Card Promo'), ('general', 'General Promo')], default='general', max_length=20)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=3, help_text='Discount amount (percentage or fixed KWD amount)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Maximum number of times this coupon can be used (null = unlimited)', null=True)),
                ('current_uses', models.PositiveIntegerField(default=0, help_text='Number of times this coupon has been used')),
                ('max_uses_per_user', models.PositiveIntegerField(default=1, help_text='Maximum uses per user')),
                ('min_order_amount', models.DecimalField(decimal_places=3, default=0, help_text='Minimum order amount required to use this coupon (KWD)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=3, help_text='Maximum discount amount for percentage-based coupons (KWD)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, help_text='Coupon valid from this date')),
                ('valid_until', models.DateTimeField(blank=True, help_text='Coupon valid until this date (null = no expiry)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this coupon currently active?')),
                ('is_featured', models.BooleanField(default=False, help_text='Show as featured card promo')),
                ('card_color', models.CharField(blank=True, help_text='Hex color for card display (e.g., #FF5733)', max_length=7, null=True)),
                ('card_icon', models.CharField(blank=True, help_text='Icon name for card display', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(db_index=True, help_text='User ID who used the coupon', max_length=255)),
                ('order_id', models.CharField(blank=True, help_text='Order ID where coupon was used', max_length=255, null=True)),
                ('discount_amount', models.DecimalField(decimal_places=3, help_text='Actual discount amount applied (KWD)', max_digits=10)),
                ('order_amount', models.DecimalField(decimal_places=3, help_text='Order amount before discount (KWD)', max_digits=10)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='Coupon.coupon')),
            ],
            options={
                'verbose_name': 'Coupon Usage',
                'verbose_name_plural': 'Coupon Usages',
                'ordering': ['-used_at'],
                'indexes': [models.Index(fields=['user_id', 'coupon'], name='Coupon_coup_user_id_898111_idx'), models.Index(fields=['order_id'], name='Coupon_coup_order_i_30c356_idx')],
            },
        ),
    ]
