from django.core.management.base import BaseCommand
from Sizes.models import DefaultMeasurement


class Command(BaseCommand):
    help = 'Populate default measurements for child category'

    def handle(self, *args, **kwargs):
        measurements_data = [
            {
                'size_name': 'newborn',
                'size_name_eng': 'Newborn',
                'size_name_ar': 'مولود جديد',
                'category': 'child',
                'length': 16.00,
                'sleeves': 8.00,
                'chest': 6.00,
                # Tailor fields (using same values as frontend display for now)
                'front_height': '16',
                'back_height': '16',
                'neck_size': '8',
                'around_legs': '12',
                'full_chest': '12',
                'half_chest': '6',
                'full_belly': '12',
                'half_belly': '6',
                'neck_to_center_belly': '10',
                'neck_to_chest_pocket': '6',
                'shoulder_width': '8',
                'arm_tall': '8',
                'arm_width_1': '4',
                'arm_width_2': '4',
                'arm_width_3': '4',
                'arm_width_4': '4',
                'is_active': True,
            },
            {
                'size_name': '3_months',
                'size_name_eng': '3 Months',
                'size_name_ar': '3 أشهر',
                'category': 'child',
                'length': 18.00,
                'sleeves': 8.50,
                'chest': 6.00,
                'front_height': '18',
                'back_height': '18',
                'neck_size': '8.5',
                'around_legs': '13',
                'full_chest': '12',
                'half_chest': '6',
                'full_belly': '13',
                'half_belly': '6.5',
                'neck_to_center_belly': '11',
                'neck_to_chest_pocket': '6.5',
                'shoulder_width': '8.5',
                'arm_tall': '8.5',
                'arm_width_1': '4.5',
                'arm_width_2': '4.5',
                'arm_width_3': '4.5',
                'arm_width_4': '4.5',
                'is_active': True,
            },
            {
                'size_name': '6_months',
                'size_name_eng': '6 Months',
                'size_name_ar': '6 أشهر',
                'category': 'child',
                'length': 20.00,
                'sleeves': 10.25,
                'chest': 6.25,
                'front_height': '20',
                'back_height': '20',
                'neck_size': '9',
                'around_legs': '14',
                'full_chest': '12.5',
                'half_chest': '6.25',
                'full_belly': '13.5',
                'half_belly': '6.75',
                'neck_to_center_belly': '12',
                'neck_to_chest_pocket': '7',
                'shoulder_width': '9',
                'arm_tall': '10.25',
                'arm_width_1': '5',
                'arm_width_2': '5',
                'arm_width_3': '5',
                'arm_width_4': '5',
                'is_active': True,
            },
            {
                'size_name': '9_months',
                'size_name_eng': '9 Months',
                'size_name_ar': '9 أشهر',
                'category': 'child',
                'length': 22.00,
                'sleeves': 10.50,
                'chest': 7.00,
                'front_height': '22',
                'back_height': '22',
                'neck_size': '9.5',
                'around_legs': '15',
                'full_chest': '14',
                'half_chest': '7',
                'full_belly': '14.5',
                'half_belly': '7.25',
                'neck_to_center_belly': '13',
                'neck_to_chest_pocket': '7.5',
                'shoulder_width': '9.5',
                'arm_tall': '10.5',
                'arm_width_1': '5.5',
                'arm_width_2': '5.5',
                'arm_width_3': '5.5',
                'arm_width_4': '5.5',
                'is_active': True,
            },
            {
                'size_name': 'one_year',
                'size_name_eng': 'One Year',
                'size_name_ar': 'سنة واحدة',
                'category': 'child',
                'length': 24.00,
                'sleeves': 10.50,
                'chest': 7.00,
                'front_height': '24',
                'back_height': '24',
                'neck_size': '10',
                'around_legs': '16',
                'full_chest': '14',
                'half_chest': '7',
                'full_belly': '15',
                'half_belly': '7.5',
                'neck_to_center_belly': '14',
                'neck_to_chest_pocket': '8',
                'shoulder_width': '10',
                'arm_tall': '10.5',
                'arm_width_1': '6',
                'arm_width_2': '6',
                'arm_width_3': '6',
                'arm_width_4': '6',
                'is_active': True,
            },
            {
                'size_name': 'two_years',
                'size_name_eng': 'Two Years',
                'size_name_ar': 'سنتان',
                'category': 'child',
                'length': 28.00,
                'sleeves': 12.00,
                'chest': 7.50,
                'front_height': '28',
                'back_height': '28',
                'neck_size': '11',
                'around_legs': '18',
                'full_chest': '15',
                'half_chest': '7.5',
                'full_belly': '16',
                'half_belly': '8',
                'neck_to_center_belly': '16',
                'neck_to_chest_pocket': '9',
                'shoulder_width': '11',
                'arm_tall': '12',
                'arm_width_1': '7',
                'arm_width_2': '7',
                'arm_width_3': '7',
                'arm_width_4': '7',
                'is_active': True,
            },
        ]

        for data in measurements_data:
            measurement, created = DefaultMeasurement.objects.get_or_create(
                size_name=data['size_name'],
                defaults=data
            )
            if created:
                self.stdout.write(
                    self.style.SUCCESS(f'Successfully created measurement: {measurement.size_name_eng}')
                )
            else:
                self.stdout.write(
                    self.style.WARNING(f'Measurement already exists: {measurement.size_name_eng}')
                )

        self.stdout.write(self.style.SUCCESS('\n✅ All measurements populated successfully!'))
