# Generated by Django 5.1.4 on 2026-01-03 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0004_alter_address_options_remove_address_area_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionalNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Notification title (e.g., 'Happy Ramadan!')", max_length=200)),
                ('message', models.TextField(help_text='Notification message body')),
                ('send_to_all', models.BooleanField(default=True, help_text='Send to all users? If unchecked, select specific users below')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='high', max_length=10)),
                ('channel', models.CharField(choices=[('push', 'Push Notification'), ('email', 'Email'), ('in_app', 'In-App')], default='push', help_text='How to deliver this notification', max_length=10)),
                ('promo_code', models.CharField(blank=True, help_text="Optional promo code (e.g., 'RAMADAN30')", max_length=50, null=True)),
                ('discount_percentage', models.IntegerField(blank=True, help_text='Optional discount percentage (e.g., 30 for 30% off)', null=True)),
                ('scheduled_time', models.DateTimeField(blank=True, help_text='Schedule for later? Leave blank to send immediately', null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_count', models.IntegerField(default=0, help_text='Number of users who received this notification')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who created this notification', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('target_users', models.ManyToManyField(blank=True, help_text="Select specific users (only if 'Send to all' is unchecked)", to='User.profile')),
            ],
            options={
                'verbose_name': 'Promotional Notification',
                'verbose_name_plural': 'Promotional Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CartAbandonmentTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_items_count', models.IntegerField(default=0)),
                ('cart_total', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('cart_last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('order_completed', models.BooleanField(default=False)),
                ('order_completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_abandonments', to='User.profile')),
            ],
            options={
                'verbose_name': 'Cart Abandonment',
                'verbose_name_plural': 'Cart Abandonments',
                'ordering': ['-cart_last_updated'],
                'indexes': [models.Index(fields=['notification_sent', 'cart_last_updated'], name='Notificatio_notific_80f200_idx')],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order_placed', 'Order Placed'), ('order_confirmed', 'Order Confirmed'), ('order_packed', 'Order Packed'), ('out_for_delivery', 'Out for Delivery'), ('order_delivered', 'Order Delivered'), ('order_cancelled', 'Order Cancelled'), ('cart_abandoned', 'Cart Abandoned'), ('promotional', 'Promotional Offer'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed')], max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('channel', models.CharField(choices=[('push', 'Push Notification'), ('email', 'Email'), ('in_app', 'In-App')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('was_sent', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_received', to='User.profile')),
                ('promotional_notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Notification.promotionalnotification')),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='Notificatio_created_d8837a_idx'), models.Index(fields=['user', '-created_at'], name='Notificatio_user_id_795731_idx'), models.Index(fields=['notification_type'], name='Notificatio_notific_8c9f2b_idx')],
            },
        ),
    ]
