from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.dashboard_view, name='dashboard'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('orders/', views.orders_view, name='orders'),
    path('orders/<int:order_id>/', views.order_detail_view, name='order_detail'),
    path('orders/<int:order_id>/update-status/', views.update_order_status, name='update_order_status'),
    path('designs/', views.designs_view, name='designs'),
    path('designs/create/', views.create_design_item, name='create_design_item'),
    path('designs/get/<str:component_type>/<int:item_id>/', views.get_design_item, name='get_design_item'),
    path('designs/get-fabric-colors/<int:fabric_type_id>/', views.get_fabric_colors, name='get_fabric_colors'),
    path('designs/update/', views.update_design_item, name='update_design_item'),
    path('designs/update-status/', views.update_design_status, name='update_design_status'),
    path('designs/update-fabric-relation/', views.update_fabric_relation, name='update_fabric_relation'),
    path('designs/update-image/', views.update_image, name='update_image'),
    path('designs/delete-image/', views.delete_image, name='delete_image'),
    path('designs/delete/', views.delete_design_item, name='delete_design_item'),
    path('users/', views.users_view, name='users'),
    path('users/<int:user_id>/', views.user_detail_view, name='user_detail'),
    path('users/<int:user_id>/update/', views.update_user, name='update_user'),
    path('sizes/', views.user_sizes_view, name='user_sizes'),
    path('payments/', views.payments_view, name='payments'),
    path('coupons/', views.coupons_view, name='coupons'),
    path('coupons/create/', views.create_coupon, name='create_coupon'),
    path('coupons/<int:coupon_id>/update/', views.update_coupon, name='update_coupon'),
    path('coupons/<int:coupon_id>/delete/', views.delete_coupon, name='delete_coupon'),
    path('addresses/', views.addresses_view, name='addresses'),
    path('addresses/<int:address_id>/update/', views.update_address, name='update_address'),
    path('banners/', views.banners_view, name='banners'),
    path('banners/create/', views.create_banner, name='create_banner'),
    path('banners/<int:banner_id>/update/', views.update_banner, name='update_banner'),
    path('banners/<int:banner_id>/delete/', views.delete_banner, name='delete_banner'),
    path('user-designs/', views.user_designs_view, name='user_designs'),
    path('user-designs/<int:design_id>/delete/', views.delete_user_design, name='delete_user_design'),
    path('inventory/', views.inventory_view, name='inventory'),
    path('inventory/add-stock/', views.add_stock, name='add_stock'),
    path('inventory/reduce-stock/', views.reduce_stock, name='reduce_stock'),
    path('delivery-settings/', views.delivery_settings_view, name='delivery_settings'),
    path('delivery-settings/update/', views.update_delivery_settings, name='update_delivery_settings'),
    path('about/', views.about_view, name='about'),
    path('about/update/', views.update_about, name='update_about'),
    path('terms/', views.terms_view, name='terms'),
    path('terms/update/', views.update_terms, name='update_terms'),
]
