# Generated by Django 5.0.7 on 2025-02-06 21:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(default='INV4898', max_length=100)),
                ('full_name', models.CharField(default='', max_length=200)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('longitude', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('latitude', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('address_name', models.CharField(blank=True, max_length=80, null=True)),
                ('Area', models.CharField(blank=True, max_length=150, null=True)),
                ('block', models.CharField(blank=True, max_length=100, null=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('house', models.CharField(blank=True, max_length=100, null=True)),
                ('apartment', models.CharField(blank=True, max_length=10, null=True)),
                ('floor', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=13)),
                ('payment_option', models.CharField(max_length=30)),
                ('total_price', models.DecimalField(decimal_places=3, max_digits=9)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Ready', 'Ready'), ('Delivering', 'Delivering'), ('Complete', 'Complete')], default='Pending', max_length=10)),
                ('asap_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_pick_up', models.BooleanField(default=False)),
                ('is_cash', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(blank=True, max_length=255, null=True)),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('unit_price', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=6)),
                ('net_amount', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=6)),
                ('discount', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=6)),
                ('quantity', models.IntegerField(default=1)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('product_size', models.CharField(blank=True, max_length=10, null=True)),
                ('cover', models.URLField(blank=True, max_length=600, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Purchase.purchase')),
            ],
        ),
    ]
