# Generated by Django 5.0.7 on 2025-11-07 06:47

import Purchase.models
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Design', '0010_fabriccolor_alter_buttonstriptype_options_and_more'),
        ('Purchase', '0001_initial'),
        ('Sizes', '0002_defaultmeasurement_custommeasurement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Purchase Order', 'verbose_name_plural': 'Purchase Orders'},
        ),
        migrations.AddField(
            model_name='item',
            name='selected_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Sizes.sizes'),
        ),
        migrations.AddField(
            model_name='item',
            name='user_design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='Design.userdesign'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=9),
        ),
        migrations.AlterField(
            model_name='item',
            name='net_amount',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=9),
        ),
        migrations.AlterField(
            model_name='item',
            name='product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit_price',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=9),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='invoice_number',
            field=models.CharField(default=Purchase.models.generate_invoice_number, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Ready', 'Ready'), ('Delivering', 'Delivering'), ('Complete', 'Complete'), ('Cancelled', 'Cancelled')], default='Pending', max_length=15),
        ),
    ]
