# Generated by Django 5.0.7 on 2025-12-05 10:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0002_alter_item_options_alter_purchase_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_days', models.IntegerField(default=5, help_text="Number of days for delivery (e.g., 'Receive within X days')")),
                ('delivery_cost', models.DecimalField(decimal_places=3, default=Decimal('2.000'), help_text='Delivery cost in KWD', max_digits=5)),
                ('is_active', models.BooleanField(default=True, help_text='Only one settings record should be active at a time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Delivery Settings',
                'verbose_name_plural': 'Delivery Settings',
                'ordering': ['-is_active', '-updated_at'],
            },
        ),
    ]
