# Generated by Django 5.0.7 on 2025-12-09 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0003_deliverysettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=9)),
                ('currency', models.CharField(default='KWD', max_length=3)),
                ('track_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('payzah_payment_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('captured', 'Captured'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=15)),
                ('payzah_reference_code', models.CharField(blank=True, max_length=100, null=True)),
                ('knet_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_number', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_date', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_status_raw', models.CharField(blank=True, help_text='Raw status from Payzah', max_length=50, null=True)),
                ('udf1', models.CharField(blank=True, max_length=255, null=True)),
                ('udf2', models.CharField(blank=True, max_length=255, null=True)),
                ('udf3', models.CharField(blank=True, max_length=255, null=True)),
                ('udf4', models.CharField(blank=True, max_length=255, null=True)),
                ('udf5', models.CharField(blank=True, max_length=255, null=True)),
                ('redirect_url', models.URLField(blank=True, max_length=500, null=True)),
                ('success_url', models.URLField(blank=True, max_length=500, null=True)),
                ('error_url', models.URLField(blank=True, max_length=500, null=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=200, null=True, unique=True)),
                ('verified_with_gateway', models.BooleanField(default=False)),
                ('gateway_verification_attempts', models.IntegerField(default=0)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purchase', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='Purchase.purchase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Transaction',
                'verbose_name_plural': 'Payment Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['track_id'], name='Purchase_pa_track_i_7378fd_idx'), models.Index(fields=['payzah_payment_id'], name='Purchase_pa_payzah__840de4_idx'), models.Index(fields=['user', 'status'], name='Purchase_pa_user_id_6324af_idx'), models.Index(fields=['created_at'], name='Purchase_pa_created_0bfbc1_idx')],
            },
        ),
    ]
