# Generated by Django 5.0.7 on 2025-12-15 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0004_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='design_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='size_details',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
