# Generated by Django 5.0.7 on 2025-12-15 19:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0005_item_design_details_item_size_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=9),
        ),
    ]
