# Generated by Django 5.0.7 on 2025-12-15 19:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0006_purchase_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='discount_amount',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=9),
        ),
    ]
