# Generated by Django 5.0.7 on 2025-12-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0007_purchase_coupon_code_purchase_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default='Custom Design', max_length=100),
        ),
    ]
