# Generated by Django 5.0.7 on 2025-12-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0008_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='cancelled_by',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('admin', 'Admin')], max_length=20, null=True),
        ),
    ]
