# Generated by Django 5.0.7 on 2025-12-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0009_purchase_cancelled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
