# Generated by Django 5.0.7 on 2025-12-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0012_update_existing_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text='When order was cancelled', null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, help_text='When order was confirmed', null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='When order was delivered', null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='pending_at',
            field=models.DateTimeField(blank=True, help_text='When order was placed', null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='shipping_at',
            field=models.DateTimeField(blank=True, help_text='When order was shipped', null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='working_at',
            field=models.DateTimeField(blank=True, help_text='When work started on order', null=True),
        ),
    ]
