# Generated by Django 5.1.4 on 2025-12-20 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0016_item_discount_percentage'),
        ('User', '0004_alter_address_options_remove_address_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='selected_address',
            field=models.ForeignKey(blank=True, help_text="Select from user's saved addresses (Home/Work/etc.)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='User.address'),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount_percentage',
            field=models.IntegerField(blank=True, help_text='Discount percentage (15, 10, or 5)', null=True),
        ),
    ]
