# Generated by Django 6.0 on 2025-12-20 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0016_item_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='discount_percentage',
            field=models.IntegerField(blank=True, help_text='Discount percentage (15, 10, or 5)', null=True),
        ),
    ]
