# Generated by Django 6.0 on 2025-12-22 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0017_add_selected_address_to_purchase'),
        ('Purchase', '0017_alter_item_discount_percentage'),
    ]

    operations = [
    ]
