# Generated by Django 6.0 on 2025-12-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0018_merge_20251222_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
