# Generated by Django 6.0 on 2025-12-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0019_alter_purchase_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='product_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
