# Generated by Django 6.0 on 2025-12-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0020_alter_item_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='product_size',
            field=models.TextField(blank=True, null=True),
        ),
    ]
