# Generated by Django 5.1.4 on 2025-12-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0021_alter_item_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverysettings',
            name='whatsapp_support',
            field=models.CharField(default='+96500000000', help_text='WhatsApp support number with country code (e.g., +96500000000)', max_length=20),
        ),
    ]
