# Generated by Django 5.1.4 on 2025-12-30 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0022_deliverysettings_whatsapp_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(default='About Us', max_length=255)),
                ('title_ar', models.CharField(default='من نحن', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Us Content',
                'verbose_name_plural': 'About Us Content',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('about', 'About'), ('mission', 'Mission'), ('values', 'Values')], max_length=20)),
                ('title_en', models.CharField(max_length=255)),
                ('title_ar', models.CharField(max_length=255)),
                ('content_en', models.TextField(blank=True, help_text='For about and mission sections', null=True)),
                ('content_ar', models.TextField(blank=True, help_text='For about and mission sections', null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='Purchase.aboutus')),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Sections',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255)),
                ('title_ar', models.CharField(max_length=255)),
                ('description_en', models.TextField()),
                ('description_ar', models.TextField()),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='Purchase.aboutsection')),
            ],
            options={
                'verbose_name': 'About Value',
                'verbose_name_plural': 'About Values',
                'ordering': ['order'],
            },
        ),
    ]
