# Generated by Django 5.1.4 on 2025-12-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0023_aboutus_aboutsection_aboutvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutvalue',
            name='section',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='content_ar',
            field=models.TextField(blank=True, help_text='About Us content in Arabic (supports HTML)', null=True),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='content_en',
            field=models.TextField(blank=True, help_text='About Us content in English (supports HTML)', null=True),
        ),
        migrations.DeleteModel(
            name='AboutSection',
        ),
        migrations.DeleteModel(
            name='AboutValue',
        ),
    ]
