# Generated by Django 5.1.4 on 2025-12-30 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0024_remove_aboutvalue_section_aboutus_content_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(default='Terms and Conditions', max_length=255)),
                ('title_ar', models.CharField(default='الشروط والأحكام', max_length=255)),
                ('content_en', models.TextField(blank=True, help_text='Terms and Conditions content in English (supports HTML)', null=True)),
                ('content_ar', models.TextField(blank=True, help_text='Terms and Conditions content in Arabic (supports HTML)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Terms and Conditions Content',
                'verbose_name_plural': 'Terms and Conditions Content',
                'ordering': ['-created_at'],
            },
        ),
    ]
