# Generated by Django 5.1.4 on 2026-01-11 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0025_termsandconditions'),
        ('Sizes', '0004_alter_defaultmeasurement_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='selected_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sizes.sizes'),
        ),
    ]
