import cloudinary.uploader

def hableImageUpload(img):
    """
    Handle image upload from base64 encoded data to Cloudinary
    Expected format: {"image": "base64_string", "name": "filename.jpg"}
    Returns: Cloudinary public_id (URL will be auto-generated by CloudinaryField)
    """
    try:
        # Check if img is a dict and has required keys
        if isinstance(img, dict) and img.get("image") and img.get("name"):
            image = img["image"]
            name = img["name"]

            # Upload to Cloudinary
            # Cloudinary accepts base64 data with the prefix "data:image/...;base64,"
            # We need to add this prefix if it's not already there
            if not image.startswith('data:'):
                # Determine the image type from the file extension
                ext = name.split('.')[-1].lower()
                mime_type_map = {
                    'jpg': 'jpeg',
                    'jpeg': 'jpeg',
                    'png': 'png',
                    'gif': 'gif',
                    'webp': 'webp'
                }
                mime_type = mime_type_map.get(ext, 'jpeg')
                image = f"data:image/{mime_type};base64,{image}"

            # Upload to Cloudinary
            upload_result = cloudinary.uploader.upload(image, folder="FabricType")

            # Return the public_id or secure_url
            # CloudinaryField can work with either, but public_id is preferred
            return upload_result.get('public_id') or upload_result.get('secure_url')
        else:
            # If not in expected format, return None or raise error
            print(f"Warning: Invalid image format received: {type(img)}, {img}")
            return None
    except Exception as e:
        print(f"Error in hableImageUpload: {str(e)}")
        raise