# Generated by Django 5.0.7 on 2025-05-27 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=80)),
                ('front_hight', models.CharField(max_length=80)),
                ('back_hight', models.CharField(max_length=80)),
                ('around_neck', models.CharField(max_length=80)),
                ('around_legs', models.CharField(max_length=80)),
                ('full_chest', models.CharField(max_length=80)),
                ('half_chest', models.CharField(max_length=80)),
                ('full_belly', models.CharField(max_length=80)),
                ('half_belly', models.CharField(max_length=80)),
                ('neck_to_center_belly', models.CharField(max_length=80)),
                ('neck_to_chest', models.CharField(max_length=80)),
                ('shoulders_width', models.CharField(max_length=80)),
                ('arm_tall', models.CharField(max_length=80)),
                ('arm_width_one', models.CharField(max_length=80)),
                ('arm_width_two', models.CharField(max_length=80)),
                ('arm_width_three', models.CharField(max_length=80)),
                ('arm_width_four', models.CharField(max_length=80)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
