# Generated by Django 5.0.7 on 2025-12-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sizes', '0002_defaultmeasurement_custommeasurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaultmeasurement',
            name='category',
            field=models.CharField(choices=[('child', 'Child'), ('adult', 'Adult'), ('baby', 'Baby')], default='child', help_text='Category: child, adult, or baby', max_length=20),
        ),
        migrations.AddField(
            model_name='defaultmeasurement',
            name='chest',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Chest measurement in inches (الصدر)', max_digits=5),
        ),
        migrations.AddField(
            model_name='defaultmeasurement',
            name='length',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Length/Height in inches (طول)', max_digits=5),
        ),
        migrations.AddField(
            model_name='defaultmeasurement',
            name='size_name_ar',
            field=models.CharField(default='', help_text="Arabic name (e.g., 'مولود جديد', '3 أشهر')", max_length=80),
        ),
        migrations.AddField(
            model_name='defaultmeasurement',
            name='size_name_eng',
            field=models.CharField(default='', help_text="English name (e.g., 'Newborn', '3 Months')", max_length=80),
        ),
        migrations.AddField(
            model_name='defaultmeasurement',
            name='sleeves',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Sleeves measurement in inches (الاكمام)', max_digits=5),
        ),
    ]
