# Generated by Django 5.0.7 on 2025-12-15 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sizes', '0003_defaultmeasurement_category_defaultmeasurement_chest_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='defaultmeasurement',
            options={'ordering': ['timestamp'], 'verbose_name': 'Default Measurement', 'verbose_name_plural': 'Default Measurements'},
        ),
    ]
