# Generated by Django 5.0.7 on 2025-02-06 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Fee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_name', models.CharField(max_length=80)),
                ('block', models.CharField(max_length=10)),
                ('street', models.CharField(max_length=100)),
                ('house', models.CharField(max_length=100)),
                ('apartment', models.CharField(blank=True, max_length=10, null=True)),
                ('floor', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(max_length=13)),
                ('longitude', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('latitude', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('isDefault', models.BooleanField(default=False)),
                ('Area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Fee.fee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=200)),
                ('premission', models.CharField(choices=[('User', 'User'), ('Admin', 'Admin'), ('Data-Entry', 'Data-Entry'), ('Partner', 'Partner'), ('Accountant', 'Accountant'), ('Driver', 'Driver'), ('Vendor', 'Vendor')], max_length=80)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
