# Generated by Django 5.0.7 on 2025-12-09 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='device_id',
            field=models.CharField(blank=True, help_text='Unique device identifier', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='device_name',
            field=models.CharField(blank=True, help_text='Device name (e.g., Samsung Galaxy S21)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='device_type',
            field=models.CharField(blank=True, help_text='Device type (android/ios)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fcm_token',
            field=models.TextField(blank=True, help_text='Firebase Cloud Messaging token for push notifications', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_fcm_update',
            field=models.DateTimeField(auto_now=True, help_text='Last time FCM token was updated'),
        ),
    ]
