# Generated by Django 5.0.7 on 2025-12-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_profile_device_id_profile_device_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='User phone number with country code', max_length=20, null=True),
        ),
    ]
