# Generated by Django 5.0.7 on 2025-12-14 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_profile_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-isDefault', '-created_at'], 'verbose_name_plural': 'Addresses'},
        ),
        migrations.RemoveField(
            model_name='address',
            name='Area',
        ),
        migrations.RemoveField(
            model_name='address',
            name='address_name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='house',
        ),
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('other', 'Other')], default='home', help_text='Address type (Home/Work/Other)', max_length=10),
        ),
        migrations.AddField(
            model_name='address',
            name='building',
            field=models.CharField(blank=True, default='', help_text='Building/House number', max_length=50),
        ),
        migrations.AddField(
            model_name='address',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='custom_label',
            field=models.CharField(blank=True, help_text="Custom address label if type is 'other'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='full_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='full_name',
            field=models.CharField(blank=True, default='', help_text="Recipient's full name", max_length=200),
        ),
        migrations.AddField(
            model_name='address',
            name='governorate',
            field=models.CharField(blank=True, default='', help_text='Governorate (e.g., Ahmadi)', max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='apartment',
            field=models.CharField(blank=True, help_text='Apartment number', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='block',
            field=models.CharField(blank=True, default='', help_text='Block number', max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='floor',
            field=models.CharField(blank=True, help_text='Floor number', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='isDefault',
            field=models.BooleanField(default=False, help_text='Is this the default address?'),
        ),
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone_number',
            field=models.CharField(help_text='Contact phone number with country code', max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(blank=True, default='', help_text='Street number', max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='address',
            name='area',
            field=models.CharField(blank=True, default='', help_text='Area/Region (e.g., Sabahiya)', max_length=100),
        ),
    ]
