# Generated by Django 5.1.4 on 2026-01-11 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_alter_address_options_remove_address_area_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForceLogoutUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='force_logout', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Force Logout User',
                'verbose_name_plural': 'Force Logout Users',
                'db_table': 'force_logout_users',
            },
        ),
    ]
