# Generated by Django 5.1.4 on 2025-12-26 05:14

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Banner title (for admin reference)', max_length=200)),
                ('image_en', cloudinary.models.CloudinaryField(help_text='Banner image for English language', max_length=255, verbose_name='banner_english')),
                ('image_ar', cloudinary.models.CloudinaryField(help_text='Banner image for Arabic language', max_length=255, verbose_name='banner_arabic')),
                ('is_active', models.BooleanField(default=True, help_text='Active banners are shown in the app')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
